INSERT INTO CLIENT (NOM ,COGNOMS ,DATA_ALTA ) VALUES ('Joana','Petita','2000-05-14');
INSERT INTO CLIENT (NOM ,COGNOMS ,DATA_ALTA ) VALUES ('Juan','Faro','0000-12-24');
INSERT INTO CLIENT (NOM ,COGNOMS ,DATA_ALTA ) VALUES ('Pepe','Petita','0500-09-08');